# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(default=1)),
                ('date_today', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 4, 17, 16, 49, 4, 812000))),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Screen_Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Date')),
                ('movie_screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Screen')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=30)),
                ('theater_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='screen_select',
            name='show_screen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Show'),
        ),
        migrations.AddField(
            model_name='screen_select',
            name='theater_screen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Theater'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='screen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Screen'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Show'),
        ),
        migrations.AddField(
            model_name='booking',
            name='theater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Theater'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='screen_select',
            unique_together=set([('theater_screen_id', 'show_screen_id', 'screen_id', 'date_screen_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('theater_id', 'movie_id', 'show_id', 'screen_id', 'seat', 'date_id')]),
        ),
    ]
