# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 17, 13, 10, 859000)),
        ),
    ]
