# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20180417_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 20, 9, 40, 30, 399000)),
        ),
    ]
