# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20180420_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 20, 16, 0, 38, 369000)),
        ),
    ]
